
# target library for lib rule
LIBTARGET=libsib.a

# objects to be built for lib rule
OBJECTS = 				\
Action.o \
Application.o \
Cell.o \
FunctionDictionary.o \
Initializer.o \
LispApplication.o \
Properties.o \
Scalar.o \
Tokenizer.o \
Writer.o \
#

TESTS=	\
Scalar_test.o \
Cell_test.o \
Writer_test.o \
#

MAYBE=	\
#

#SRCS = State.cpp StateMachine.cpp Event.cpp Entity.cpp InternalEntityInstance.cpp Declaration.cpp Initializer.cpp GrammarUtil.cpp

#HDRS = State.hpp StateMachine.hpp Action.hpp Event.hpp Declaration.hpp \
		Entity.hpp InternalEntityInstance.hpp Declaration.hpp Initializer.hpp \
		GrammarUtil.hpp


APPS= ref_counted_test Cell_test Scalar_test Writer_test

# 
include ../Makefile.General


